### ISSUE TITLE
Tag v1.1.6 does not compile

### ISSUE THREAD

**Issue by mthalmei** [galactrum/galactrum#6]
When checking out tag v1.1.6 there is a compilation error because of a syntax error in commit 849f525d1bae6f78bbe0bc10a432634f953eff7d.
Please update the v1.1.6 tag to commit 8c465e08ee71a2da9302ae05b2c1db03ad6333c9.

**Comment by shensu** [comment]
Building off of master works.

**Comment by Tr4sK** [comment]
Please, fix validation.cpp in tag 1.1.6 to have a clean tag.
[0001-typo.patch.txt](https://github.com/galactrum/galactrum/files/2229887/0001-typo.patch.txt)
